### ISSUE TITLE
Missed nfos

### ISSUE THREAD

**Issue by kamil445** [model-map/EmpressNfo#1]
Anno 1800
Mortal kombat 11
Yakuza like a dragon
SOULCALIBUR VI
and more

**Comment by jayantchandra** [comment]
Yakuza like a dragon is on #12

> Anno 1800 Mortal kombat 11 Yakuza like a dragon SOULCALIBUR VI and more

Do you have them?

**Comment by kamil445** [comment]
I seen them only in png format

**Comment by jayantchandra** [comment]
if you know the website the respective resources are on then i'll fetch them. I got mine from Empress' own upload page

**Comment by deohanis** [comment]
> Anno 1800 Mortal kombat 11 Yakuza like a dragon SOULCALIBUR VI and more

I can definitely try to get those for you. Could you please expand the list of the games you found missing?

Additionally, @model-map I had a question regarding the existing order of the <code>.nfo</code> files, should they be ordered from most recent to oldest?

**Comment by jayantchandra** [comment]
@1uvnoa I'm not even sure of the ones I'm missing tbh. I fetched everything I found on 1337x (to the best of knowledge) so ideally it should've already been a complete DB. But since its not and since there's no index of Empress' uploads in chronological order the task becomes manual. @kamil445 was very kind to mention a few that were missing. And a few of those were uploaded by you (thank you!) so I guess we're left with manual execution of tallying and finding the missing links.

Regarding your second question, the order of .nfo should be from most recent to oldest. This is so users who'd like to only read the recent can find it in they eye-view and those that are willing to expend effort to go through it chronologically can scroll down and begin reading until they climb up and reach the summit (signifying that they begun from the bottom and reached the top. A symbolic climb. I know it sounds a bit goofy but I like such symbolism :) )

**Comment by skylandersNFC** [comment]
Anno.1800.Crackfix-EMPRESS: https://pastebin.com/raw/d38USm9H

**Comment by skylandersNFC** [comment]
AEW.Fight.Forever-EMPRESS: https://pastebin.com/raw/dRYN4Q0f

**Comment by skylandersNFC** [comment]
Zombie.Army.4.Dead.War.Crackfix.READNFO-EMPRESS: https://pastebin.com/raw/nP8VuN4w
Zombie.Army.4.Dead.War.Crackfix.V2.READNFO-EMPRESS: https://pastebin.com/raw/Ag8wafxD
Zombie.Army.4.Dead.War.Crackfix.V3-EMPRESS: https://pastebin.com/raw/PDhwsine

**Comment by skylandersNFC** [comment]
Assassins.Creed.Odyssey.The.Fate.of.Atlantis.READNFO-EMPRESS: https://pastebin.com/raw/8hSdNKGh

**Comment by skylandersNFC** [comment]
Borderlands.3.Super.Deluxer.Edition-EMPRESS: https://pastebin.com/raw/6BDSN2yC

**Comment by skylandersNFC** [comment]
Planet.Zoo.EMPRESS: https://pastebin.com/raw/HtLBACUi

**Comment by skylandersNFC** [comment]
Still missing:

TEKKEN.7.CAVE.OF.ENLIGHTENMENT-EMPRESS
SOUlCALIBUR.VI.READNFO-EMPRESS
SOULCALIBUR.VI.DLC.UNLOCKER-EMPRESS

**Comment by skylandersNFC** [comment]
Just realized i can directly upload the NFOs to nfomation.net, instead of spamming them here O.o

https://nfomation.net/info/1722943468.AEW.Fight.Forever-EMPRESS.nfo
https://nfomation.net/info/1722943472.Anno.1800.Crackfix-EMPRESS.nfo
https://nfomation.net/info/1722943475.Anno.1800.Digital.Deluxe.Edition-EMPRESS.nfo
https://nfomation.net/info/1722943675.Assassins.Creed.Odyssey.The.Fate.of.Atlantis.READNFO-EMPRESS.nfo
https://nfomation.net/info/1722943485.Borderlands.3.Physcho.Kreig.and.the.Fantastic.Fustercluck.Crackfix-EMPRESS.nfo
https://nfomation.net/info/1722943489.Borderlands.3.Super.Deluxer.Edition-EMPRESS.nfo
https://nfomation.net/info/1722943493.Planet.Zoo.EMPRESS.nfo
https://nfomation.net/info/1722943497.Zombie.Army.4.Dead.War.Crackfix.READNFO-EMPRESS.nfo
https://nfomation.net/info/1722943501.Zombie.Army.4.Dead.War.Crackfix.V2.READNFO-EMPRESS.nfo
https://nfomation.net/info/1722943505.Zombie.Army.4.Dead.War.Crackfix.V3-EMPRESS.nfo
https://nfomation.net/info/1722943508.Zombie.Army.4.Dead.War-EMPRESS.nfo
https://nfomation.net/info/1722944169.TEKKEN.7.CAVE.OF.ENLIGHTENMENT-EMPRESS.nfo

Those two i was only able to find them on xrel.to (no idea if they can be used/referenced this way):

[SOUlCALIBUR.VI.READNFO-EMPRESS](https://www.xrel.to/p2p/235846-SOUlCALIBUR-VI-READNFO-EMPRESS/nfo.html)
[SOULCALIBUR.VI.DLC.UNLOCKER-EMPRESS](https://www.xrel.to/p2p/235859-SOULCALIBUR-VI-DLC-UNLOCKER-EMPRESS/nfo.html)

**Comment by deohanis** [comment]
Hey there @skylandersNFC, thank you so much for pointing out the missing nfos and taking your time to upload them on nfomation.  

I will definitely take a look onto those and get back to you. :)

**Comment by jayantchandra** [comment]
Closed, Thanks deohanis
